### ISSUE TITLE
ブランチ運用の決定（命名規則など）

### ISSUE THREAD

**Issue by t-isano** [nacomer/nacomer#35]
何か決めるかどうか
(A) 決めずに自由にブランチ作成する
(B) feature/xxxx, bug/xxxx, support/xxx あたりで運用する？
（GitHubの issue 番号と紐付けとかしてると便利だったりする？）

プルリクエストにissue紐付ける？
（issue からも紐付けできそう）

**Comment by s-w-high** [comment]
feature/番号-機能名

例：feature/35-branchstrategy
